"""Description of the migration

Revision ID: 596bffb8273e
Revises: 78d5288a345c
Create Date: 2024-09-11 11:17:25.046165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596bffb8273e'
down_revision = '78d5288a345c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winner', sa.Column('prize_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winner', 'prize_amount')
    # ### end Alembic commands ###
