"""Add chat_id to Channel model

Revision ID: 6f4af621c31d
Revises: b881173c1266
Create Date: 2024-08-28 06:46:02.587967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4af621c31d'
down_revision = 'b881173c1266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.add_column('participant', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'participant', 'user', ['user_id'], ['id'])
    op.drop_column('participant', 'telegram_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('telegram_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'user_id')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_table('winner')
    # ### end Alembic commands ###
