"""Description of the migration

Revision ID: ea5b14b13a17
Revises: 
Create Date: 2024-09-11 02:26:31.673053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5b14b13a17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaway', sa.Column('winners_announced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaway', 'winners_announced')
    # ### end Alembic commands ###
